In [2]:
import torch

In [19]:
#1-D Tensor
a = torch.tensor([1,1,1])
print(a)
print(a.size())
print(a.shape)

tensor([1, 1, 1])
torch.Size([3])
torch.Size([3])


In [20]:
#2-D Tensor
b = torch.tensor([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
print(b)
print(b.size())
print(b.shape)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
torch.Size([4, 3])
torch.Size([4, 3])


In [21]:
#Get the height/number of rows of a and b
print(a.shape[0])
print(b.shape[0])

3
4


In [22]:
c = torch.FloatTensor([[1,1,1],[2,2,2],[3,3,3]])
#c = torch.tensor([[1,1,1],[2,2,2],[3,3,3]], dtype=torch.float)
print(c)
print(c.dtype)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])
torch.float32


In [23]:
d = torch.DoubleTensor([[1,1,1],[2,2,2],[3,3,3]])
#d = torch.tensor([[1,1,1],[2,2,2],[3,3,3]], dtype=torch.double)
print(d)
print(d.dtype)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]], dtype=torch.float64)
torch.float64


In [24]:
print(c.mean())
print(d.mean())

tensor(2.)
tensor(2., dtype=torch.float64)


In [25]:
print(c.std())
print(d.std())

tensor(0.8660)
tensor(0.8660, dtype=torch.float64)


Reshape

In [41]:
#Note: if one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,6))
print(b.view(4,3))


tensor([[1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [3],
        [3],
        [3],
        [4],
        [4],
        [4]])
tensor([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])
tensor([[1, 1, 1, 2, 2, 2],
        [3, 3, 3, 4, 4, 4]])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])


In [43]:
#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)

tensor([[1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]])
torch.Size([1, 12])


In [45]:
#Reshape 3D tensor
#Create a 3D tensor with 2 channels, 3 rows and 4 columns
three_dim = torch.randn(2,3,4)
print(three_dim)
print(three_dim.view(2,12)) # reshape to 2 rows, 12 columns
print(three_dim.view(2,-1))

tensor([[[-1.2406,  0.3689,  1.2839, -2.0855],
         [-0.7604,  2.1656,  0.1488,  0.6354],
         [-0.0058,  0.7187, -0.4386, -1.3835]],

        [[ 1.0358, -1.0167, -1.1844, -0.3862],
         [-1.1852, -0.4440, -0.5527,  0.2087],
         [ 1.3530, -0.0049, -0.4344,  0.2745]]])
tensor([[-1.2406,  0.3689,  1.2839, -2.0855, -0.7604,  2.1656,  0.1488,  0.6354,
         -0.0058,  0.7187, -0.4386, -1.3835],
        [ 1.0358, -1.0167, -1.1844, -0.3862, -1.1852, -0.4440, -0.5527,  0.2087,
          1.3530, -0.0049, -0.4344,  0.2745]])
tensor([[-1.2406,  0.3689,  1.2839, -2.0855, -0.7604,  2.1656,  0.1488,  0.6354,
         -0.0058,  0.7187, -0.4386, -1.3835],
        [ 1.0358, -1.0167, -1.1844, -0.3862, -1.1852, -0.4440, -0.5527,  0.2087,
          1.3530, -0.0049, -0.4344,  0.2745]])
